package storage

var AppendEvidenceBatchForTest = appendEvidenceBatch
var ValidateEvidenceBatchLookupsForTest = validateEvidenceBatchLookups

var NextEvidenceBatchExpiryForTest = nextEvidenceBatchExpiry

var ValidateEvidenceBatchIdentityGroupForTest = validateEvidenceBatchIdentityGroup
var ValidateEvidenceBatchBoundsForTest = validateEvidenceBatchBounds
